<a href="https://colab.research.google.com/github/jimsjoo/finance/blob/master/ALGO_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
import  numpy as np
import pandas as pd
from pandas_datareader import data as web
import warnings

In [26]:
warnings.filterwarnings('ignore')
ticker = 'FB'
df = web.DataReader(ticker, data_source='yahoo', start='2012-05-18', end='2018-03-27')

In [27]:
df = df[['Adj Close']]
# for predicting 'n' days out into the future
forecast_out = 30
df['Prediction'] = df[['Adj Close']].shift(-forecast_out)

In [28]:
X = np.array(df.drop(['Prediction'],1))
X = X[:-forecast_out]

In [29]:
y = np.array(df['Prediction'])
y = y[:-forecast_out]
y

array([ 30.77000046,  31.20000076,  31.46999931, ..., 159.38999939,
       160.05999756, 152.22000122])

In [30]:
X_train, X_test, Y_train, Y_test =train_test_split(X, y, test_size=0.2)

In [31]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(X_train, Y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [32]:
svm_confidence = svr_rbf.score(X_test, Y_test)
svm_confidence

0.9855935005328456

In [33]:
lr = LinearRegression()
lr.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
lr_confidence = lr.score(X_test, Y_test)
lr_confidence

0.9840294223600949

In [35]:
x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]
x_forecast

array([[173.1499939 ],
       [179.52000427],
       [179.96000671],
       [177.36000061],
       [176.00999451],
       [177.91000366],
       [178.99000549],
       [183.28999329],
       [184.92999268],
       [181.46000671],
       [178.32000732],
       [175.94000244],
       [176.61999512],
       [180.3999939 ],
       [179.77999878],
       [183.71000671],
       [182.33999634],
       [185.22999573],
       [184.75999451],
       [181.88000488],
       [184.19000244],
       [183.86000061],
       [185.08999634],
       [172.55999756],
       [168.1499939 ],
       [169.38999939],
       [164.88999939],
       [159.38999939],
       [160.05999756],
       [152.22000122]])

In [36]:
lr_prediction = lr.predict(x_forecast)
lr_prediction

array([177.04805542, 183.48079551, 183.92513095, 181.29952086,
       179.93622035, 181.85494016, 182.94557749, 187.28791011,
       188.94405966, 185.43990245, 182.2689814 , 179.86553903,
       180.55222805, 184.36945098, 183.74335036, 187.71205969,
       186.32855791, 189.24701704, 188.77238741, 185.86403662,
       188.19678225, 187.86353068, 189.10563899, 176.452249  ,
       171.9988171 , 173.25103375, 168.70671927, 163.15255712,
       163.82915321, 155.91195122])

In [37]:
svm_prediction = svr_rbf.predict(x_forecast)
svm_prediction

array([181.22981345, 179.13196603, 178.46636391, 176.73333377,
       173.35023143, 179.25154018, 180.17628095, 179.98497228,
       178.15284013, 180.98537206, 180.32012012, 173.50531957,
       173.57877357, 178.47582872, 178.67568712, 178.59790324,
       182.18442841, 179.12775026, 177.76911433, 181.92466298,
       177.56864776, 178.18422715, 178.63125958, 178.8939852 ,
       172.47762865, 172.86883111, 172.1848143 , 167.68980613,
       166.24091371, 160.78124411])